[package]
name = "a"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
chumsky = "0.9"
ariadne = "0.5"
serde = { version = "1", features = ["derive"] }
bincode = "1"
serde_json = "1"
ureq = "2"
